phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": True,
            "initial_mach": (0.33, "unitless"),
            "final_mach": (0.65, "unitless"),
            "mach_bounds": ((0.31, 0.67), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (23500.0, "ft"),
            "altitude_bounds": ((0.0, 24000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": True,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((45.0, 135.0), "min"),
        },
        "initial_guesses": {"time": ([0.0, 90.0], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": True,
            "initial_mach": (0.65, "unitless"),
            "final_mach": (0.7, "unitless"),
            "mach_bounds": ((0.63, 0.72), "unitless"),
            "initial_altitude": (23500.0, "ft"),
            "final_altitude": (26500.0, "ft"),
            "altitude_bounds": ((23000.0, 27000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((45.0, 135.0), "min"),
            "duration_bounds": ((15.0, 45.0), "min"),
        },
        "initial_guesses": {"time": ([90.0, 30.0], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": True,
            "initial_mach": (0.7, "unitless"),
            "final_mach": (0.7, "unitless"),
            "mach_bounds": ((0.6799999999999999, 0.72), "unitless"),
            "initial_altitude": (26500.0, "ft"),
            "final_altitude": (26500.0, "ft"),
            "altitude_bounds": ((26000.0, 27000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((60.0, 180.0), "min"),
            "duration_bounds": ((350.0, 1050.0), "min"),
        },
        "initial_guesses": {"time": ([120.0, 700.0], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": True,
            "initial_mach": (0.7, "unitless"),
            "final_mach": (0.33, "unitless"),
            "mach_bounds": ((0.31, 0.72), "unitless"),
            "initial_altitude": (26500.0, "ft"),
            "final_altitude": (0.0, "ft"),
            "altitude_bounds": ((0.0, 27000.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((410.0, 1230.0), "min"),
            "duration_bounds": ((7.5, 22.5), "min"),
        },
        "initial_guesses": {"time": ([820.0, 15.0], "min")},
    },
    "post_mission": {
        "include_landing": True,
        "constrain_range": False,
        "target_range": (6245.95, "nmi"),
    },
}
