phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.3, "unitless"),
            "final_mach": (0.6, "unitless"),
            "mach_bounds": ((0.27999999999999997, 0.62), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (24000.0, "ft"),
            "altitude_bounds": ((0.0, 24500.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": True,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((25.0, 75.0), "min"),
        },
        "initial_guesses": {"time": ([0, 50], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.6, "unitless"),
            "final_mach": (0.7, "unitless"),
            "mach_bounds": ((0.58, 0.72), "unitless"),
            "initial_altitude": (24000.0, "ft"),
            "final_altitude": (28000.0, "ft"),
            "altitude_bounds": ((23500.0, 28500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((25.0, 75.0), "min"),
            "duration_bounds": ((15.0, 45.0), "min"),
        },
        "initial_guesses": {"time": ([50, 30], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.7, "unitless"),
            "final_mach": (0.7, "unitless"),
            "mach_bounds": ((0.6799999999999999, 0.72), "unitless"),
            "initial_altitude": (28000.0, "ft"),
            "final_altitude": (28000.0, "ft"),
            "altitude_bounds": ((27500.0, 28500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((40.0, 120.0), "min"),
            "duration_bounds": ((170.0, 510.0), "min"),
        },
        "initial_guesses": {"time": ([80, 340], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 5,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.7, "unitless"),
            "final_mach": (0.3, "unitless"),
            "mach_bounds": ((0.27999999999999997, 0.72), "unitless"),
            "initial_altitude": (28000.0, "ft"),
            "final_altitude": (0.0, "ft"),
            "altitude_bounds": ((0.0, 28500.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((210.0, 630.0), "min"),
            "duration_bounds": ((7.5, 22.5), "min"),
        },
        "initial_guesses": {"time": ([420, 15], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (3195, "nmi"),
    },
}
